"""Remove useless fields

Revision ID: 71744666aed6
Revises: 23580c5fc67e
Create Date: 2020-08-10 08:30:43.759215

"""
from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71744666aed6'
down_revision = '23580c5fc67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'expiry')
    op.drop_column('item', 'qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
