"""Add OpenFoodFacts ID to item

Revision ID: b37ac6d8c8f6
Revises: 71744666aed6
Create Date: 2020-08-10 08:32:21.399627

"""
from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


# revision identifiers, used by Alembic.
revision = 'b37ac6d8c8f6'
down_revision = '71744666aed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('openfoodfacts_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'openfoodfacts_id')
    # ### end Alembic commands ###
